# Generated by Django 5.2.15 on 2026-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=20)),
                ('date_added', models.DateField()),
                ('program', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['id'],
            },
        ),
    ]
